### PR TITLE
Allow listening on any interface

### PR DESCRIPTION
**Pull request by danielkucera**
Hello krolaw,

i tested both methods for listening:
- ListenAndServe correctly listens on all interfaces but broadcast responses are sent always to interface with default gateway (this is ok if you have only one interface in system)
- ListenAndServeIf listens also on all interfaces but filters packet by interface id and responds via interface where request was received (thanks to SetControlMessage magic)

so I created patch which modifies ListenAndServeIf packet filter to accept packets from all interfaces (in case you set "any") and responds on correct interface as usual. Tested and works on:

 Linux 4.8.0-37-generic #39-Ubuntu SMP Thu Jan 26 02:27:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

This might also be a solution for #22

### CODE REVIEW

**Comment by krolaw** [comment]
That's a really good idea and your patch is an improvement.  However, I'd like to use your idea as inspiration for extending serverif.go to handle multiple (specified or any) interfaces.  Would you mind looking at branch multiIf and giving your thoughts?

Thanks.

**Comment by danielkucera** [comment]
First, I also thought about array with "allowed" interfaces but I'm not sure what happens with interface indexes if you add/remove interfaces to the system while dhcp is running. I guess the numbering changes and you would need to reinitialize ifIndices. So I chose more simple approach. If you could register some callback on interface change, that might be a way.

**Comment by krolaw** [comment]
I think adding/removing network interfaces adds too much complexity (thread safety) for the rarity of hot swapping without a restart being ok.  Is this something you need?

**Comment by danielkucera** [comment]
I don't need to listen on specific interfaces, for me it's enough to listen
on any. But I wanted to point to possibe problem with your solution. You
can hot-add/remove many types of interfaces today (usb, virtual, tun/tap,
gre, even pci-ex should be possible ...)

Dňa 11. 2. 2017 4:30 dopoludnia používateľ "Richard Warburton" <
notifications@github.com> napísal:

I think adding/removing network interfaces adds too much complexity (thread
safety) for the rarity of hot swapping without a restart being ok. Is this
something you need?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/krolaw/dhcp4/pull/30#issuecomment-279117914>, or mute
the thread

**Comment by krolaw** [comment]
Fair enough, I appreciate the input, especially when your solution helped solve #22.  However, no one has yet voiced their need for hot swapping dhcp interfaces, making it a feature without a known user base.  As such, the mutex overhead and code complexity for what is essentially a howto for ServeConn, imo doesn't carry its weight.  If a user requires hot swapping I'll re-evaluate, but  keeping the example simple may be more important imo.

Any other feedback?

**Comment by danielkucera** [comment]
Ok, I agree. I don't have any other objections. :)

**Comment by DanCripe** [comment]
Actually, I have a use case for adding/removing interfaces from dhcp4. In my case, I have a docker container that is performing services (including dhcp) to multiple interfaces, and the management code adds and removes interfaces from the container. These aren't "new" interfaces, as such, but they are new to the namespace. I, also, have a fork in which I'm solving the same problem. In my case, I'm using sync.Mutex to prevent simultaneous access to protected data structures, and channels to communicate incoming packets (so there can be individual handlers for each interface). See https://github.com/dancripe/dhcp4 for my implementation.

**Comment by krolaw** [comment]
Binding has been solved in Linux. Stopping and starting the server can be solved by a custom dhcp4.Handler. Thanks for work and suggestions.

**Pull request closed without merging**
