### PR TITLE
Add helpers for unmarshal JSON object into Options map

### PR DESCRIPTION
**Pull request by ZiroKyl**
Implements the json.Unmarshaler interface for DHCP Options map.
This adds simple way to init DHCP Options from JSON object. For example, read DHCP Options from JSON formatted config file.

P.S. `go test` also been implemented.

### CODE REVIEW

**Comment by krolaw** [comment]
Hi, IMHO I don't think that sort of functionality belongs in the dhcp4 package as it near doubles the source size, on the oft chance that the user wants to store DHCP options, in that particular JSON format.

However, I do think there is merit in having this code in a separate package, which imports the dhcp4 package for the Options type.  That way those wanting the functionality can import your package along with my one.

Thoughts?

**Comment by ZiroKyl** [comment]
I like this idea (separate package or sub package) but Go doesn't allow to do this: [How do I import Parent-package from Sub-package for method?](http://grokbase.com/t/gg/golang-nuts/143df02rm0/go-nuts-how-do-i-import-parent-package-from-sub-package-for-method):
> This does not work, you may not define a method on a type you did not
declare in your own package, exported or not.

**Comment by krolaw** [comment]
Perhaps something like:
type JSONOptions dhcp4.Options

Change object from dhcp4.Options to JSONOptions:
func (o *JSONOptions) UnmarshalJSON(b []byte) error { ... }

And when finished (in the example) cast your JSONOptions to dhcp4.Options.

**Comment by ZiroKyl** [comment]
Done. Usage:
```go
import "encoding/json"
import "github.com/krolaw/dhcp4"
import "github.com/krolaw/dhcp4/reflectDHCP"
...
var opt = dhcp4.Options{};
json.Unmarshal(strJSON, (*reflectDHCP.Options)(&opt));
```

**Comment by krolaw** [comment]
Not wanting to have misled, but I imagined the separate package would have been called something like:
github.com/ZiroKyl/JSONdhcp4

That way it's your feature, your responsibility.  I won't need to sign off or check improvements AND I can redirect requests for XML, TOML, bind, etc formats to their own packages that I also don't manage :-)

**Comment by ZiroKyl** [comment]
New repo https://github.com/ZiroKyl/reflectDHCP

> I also don't manage :-)

I understand: https://github.com/ZiroKyl/dhcp4/commit/b05b5da875555fdda29dac19c9d18226f29ed00b#diff-23900ffffef263bf9082a906ba6c278aR371

**Pull request closed without merging**
