### PR TITLE
Choose destination address as per RFC2131

### PR DESCRIPTION
**Pull request by stapelberg**
Also set the broadcast flag depending on whether we are broadcasting or not.

Both are required to correctly implement a PXE redirection server (see section
1.5.1.1 of http://www.pix.net/software/pxeboot/archive/pxespec.pdf).

This is related to https://github.com/krolaw/dhcp4/issues/35, but I haven’t tested with a relay agent, and I don’t know whether the filtering implemented in the giaddr branch is required. I can remove the GIAddr hunk from the PR if you prefer.

### CODE REVIEW

**Comment by krolaw** [comment]
Thanks for looking into this, I think it's awesome that this library is being used in all sorts of ways I haven't thought of.

My issue with allowing clients to choose arbitrary destinations by default is that some networks that this dhcp lib runs on is open (as in wifi hotspot) and this could send packets to unexpected places (i.e. wrong side of firewall or just be a DOS nuisance) - so I wouldn't want that to be the default behaviour.

I'm unsure about altering the packet prior to passing it to the handler, as this might prevent some other use case that I am unaware of from working correctly.

My suggestion would be to create your own ServeConn that decides the destination itself like conn/giaddr.go does in giaddr branch (it's the future), so you need not change server.go at all. Extending (and possibly renaming) conn/giaddr.go or creating a conn/pxe.go wouldn't impact existing users and yet would allow easy access to that functionality - i.e. just use the PXEConn.

Thoughts?

**Comment by stapelberg** [comment]
Thanks for looking at this! Replies inline:

> My issue with allowing clients to choose arbitrary destinations by default is that some networks that this dhcp lib runs on is open (as in wifi hotspot) and this could send packets to unexpected places (i.e. wrong side of firewall or just be a DOS nuisance) - so I wouldn't want that to be the default behaviour.

I haven’t looked at the RFCs in enough detail to say whether they speak to the security properties of these fields, so maybe we’ll need to do some more reading before we can make a decision on this. During the development of this package, have you by chance become familiar with other DHCP code bases and could take a quick look to see what others are doing?

> I'm unsure about altering the packet prior to passing it to the handler, as this might prevent some other use case that I am unaware of from working correctly.

That’s fair. I can change the code to pass through yIAddr to destAddr and destIP to avoid any modifications to the packet.

> My suggestion would be to create your own ServeConn that decides the destination itself like conn/giaddr.go does in giaddr branch (it's the future), so you need not change server.go at all. Extending (and possibly renaming) conn/giaddr.go or creating a conn/pxe.go wouldn't impact existing users and yet would allow easy access to that functionality - i.e. just use the PXEConn.

This would definitely be possible and safe, but wouldn’t it be better to be RFC-compliant by default?

**Comment by krolaw** [comment]
> During the development of this package, have you by chance become familiar with other DHCP code bases and could take a quick look to see what others are doing?

Sadly no, I just read the specs and implemented as I saw fit. There are other omissions. The code base was written to be simple, understandable, provide functionality for most use cases; and be extensible enough for every other case.  It's an opinionated balance, but I'm happy to debate ideas and be proven wrong.

**Comment by stapelberg** [comment]
I discovered that https://github.com/google/netboot has my use-case covered, so I’ll close this PR.

**Pull request closed without merging**
