### PR TITLE
Use 'stringer' to generate strings for MessageType

### PR DESCRIPTION
**Pull request by mdlayher**
Used the stringer utility (https://godoc.org/golang.org/x/tools/cmd/stringer) to generate strings for the `MessageType` type when `go generate` is invoked.  Added test coverage for them as well.

### CODE REVIEW

**Comment by krolaw** [comment]
Do we really need to be testing the stringer utility?

**Comment by mdlayher** [comment]
Probably not.  I just did it because it was relatively easy.  I can remove those though.

**Comment by mdlayher** [comment]
@krolaw removed tests.

**Comment by mdlayher** [comment]
Just added a `go generate` tag and updated with newer version of `stringer`.

**Pull request merged**
